FROM alpine


RUN echo 'https://nl.alpinelinux.org/alpine/v3.18/main' > /etc/apk/repositories  && \
    echo 'https://nl.alpinelinux.org/alpine/v3.18/community' >> /etc/apk/repositories

RUN apk update
RUN apk upgrade

RUN apk add --no-cache ffmpeg

CMD ["which", "ffmpeg"]